import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import './globals.css'
import Navber from "@/components/navbar/Navber";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: {
    default:"Next-14 home page",
    template: "%s | Next.js 14"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
        <Navber />
        {children}
        <Footer />
        </div>
        
      </body>
    </html>
  );
}
